### ISSUE TITLE
vue warns about the 'identity' injection not being found

### ISSUE THREAD

**Issue by fk1blow** [a7650/vue3-draggable-resizable#2]
```[Vue warn]: injection "identity" not found.```

and the code i m using:

```
<Vue3DraggableResizable
    class="editor-console"
    :initW="110"
    :initH="120"
    v-model:active="active"
    :draggable="false"
    :resizable="true"
  >
    This is a test example
  </Vue3DraggableResizable>
```

**Comment by a7650** [comment]
> `[Vue warn]: injection "identity" not found.`
> 
> and the code i m using:
> 
> ```
> <Vue3DraggableResizable
>     class="editor-console"
>     :initW="110"
>     :initH="120"
>     v-model:active="active"
>     :draggable="false"
>     :resizable="true"
>   >
>     This is a test example
>   </Vue3DraggableResizable>
> ```

This situation has been dealt with in the program, which does not affect the normal use.

**Comment by a7650** [comment]
fixed

**Comment by khalo-sa** [comment]
Hey @a7650 , thank you for this great component! 

Sadly I am still seeing this warning: "[Vue warn]: injection "identity" not found". I am using Version 1.6.1 with Vue 3.2.1.

**Comment by ErHu1993** [comment]
> Hey @a7650 , thank you for this great component!
> 
> Sadly I am still seeing this warning: "[Vue warn]: injection "identity" not found". I am using Version 1.6.1 with Vue 3.2.1.

same problem
